### ISSUE TITLE
为什么还需要psenet?

### ISSUE THREAD

**Issue by rkshuai** [JiaquanYe/TableMASTER-mmocr#21]
请问tablemaster已经预测到了cell坐标，而master可以直接对cell中的单行或者多行内容进行识别，为什么还需要psenet再检测单行坐标呢？

**Comment by delveintodetail** [comment]
why we need psenet?

When we design our method, we are afraid that the  predicted boxes by tablemaster may be not good enough for text box (instead of line) recognition, so we use detected boxes by psenet for text line recognition.  Yes, if the box prediction by tablemaster is good, you can directly use them.

**Comment by JiaquanYe** [comment]
As @delveintodetail mention，we use psenet for getting higher performance at the competition. If you got a perfect performance in locating the table cells of TableMASTER, psenet may be not necessary.

**Comment by rkshuai** [comment]
Thanks for answering, happy national day @delveintodetail @JiaquanYe
